const cfg=window.WILDKID_CONFIG||{};const grid=document.getElementById("videoGrid"),status=document.getElementById("ytStatus");let videos=[],active="all";
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
function classify(v){const t=(v.snippet?.title+" "+v.snippet?.description).toLowerCase();let c=[];if(/short|#shorts|reel/.test(t))c.push("shorts");if(/music|song|cover|original/.test(t))c.push("music");if(/bike|biker|motorcycle|moto|riding|ride/.test(t))c.push("moto");if(/travel|trip|tour|journey|road|explore|vlog/.test(t))c.push("travel","vlogs");if(/adventure|mountain|trek|camp|himalaya|beach/.test(t))c.push("adventure");return [...new Set(c)]}
function render(){let list=videos.filter(v=>active==="all"||v._cats.includes(active));grid.innerHTML=list.length?list.map(v=>{const s=v.snippet;const id=v.contentDetails?.videoId||v.id;return `<a class="video-card" href="https://www.youtube.com/watch?v=${id}" target="_blank" rel="noopener"><div class="thumb"><img src="${s.thumbnails?.high?.url||s.thumbnails?.medium?.url}" alt="${esc(s.title)}"><div class="play">▶</div></div><div class="video-info"><small>${v._cats.join(" • ")||"WILDKID VLOGS"}</small><h3>${esc(s.title)}</h3><p>${new Date(s.publishedAt).toLocaleDateString()}</p></div></a>`}).join(""):`<p>No content found for this category yet.</p>`}
async function getJSON(url){const r=await fetch(url);if(!r.ok)throw new Error(await r.text());return r.json()}
async function load(){if(!cfg.youtubeApiKey||cfg.youtubeApiKey.includes("PASTE_")){status.textContent="YouTube auto-sync is ready — add your API key in config.js.";return}
try{const base="https://www.googleapis.com/youtube/v3/";const ch=await getJSON(`${base}channels?part=contentDetails&forHandle=${encodeURIComponent(cfg.youtubeHandle)}&key=${encodeURIComponent(cfg.youtubeApiKey)}`);const uploads=ch.items?.[0]?.contentDetails?.relatedPlaylists?.uploads;if(!uploads)throw Error("Channel not found");
const data=await getJSON(`${base}playlistItems?part=snippet,contentDetails&playlistId=${uploads}&maxResults=${cfg.videosToShow||12}&key=${encodeURIComponent(cfg.youtubeApiKey)}`);videos=data.items||[];videos.forEach(v=>v._cats=classify(v));status.textContent=`Automatically synced from ${cfg.youtubeHandle}`;render()}catch(e){console.error(e);status.textContent="YouTube sync could not connect. Check config.js/API key.";}}
document.getElementById("filters").addEventListener("click",e=>{if(e.target.tagName==="BUTTON"){document.querySelectorAll("#filters button").forEach(b=>b.classList.remove("active"));e.target.classList.add("active");active=e.target.dataset.filter;render()}});
document.getElementById("menu").addEventListener("click",()=>document.getElementById("nav").classList.toggle("open"));
load();setInterval(load,Math.max(5,Number(cfg.refreshMinutes)||30)*60000);
